[package]
name = "tests-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
bus = "2.3.0"
env_logger = "0.9.0"
crossbeam-channel = "0.5.6"